<?php

namespace Database\Seeders;

use App\Models\ReleaseNote;
use Illuminate\Database\Seeder;

class ReleaseNoteSeeder extends Seeder
{
    public function run(): void
    {
        ReleaseNote::query()->delete();

        $notes = [
            [
                'title' => 'Đăng ký qua UCP & Fix Kẹt',
                'slug' => 'ucp-registration-fixstuck-20260530',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Người chơi mới phải đăng ký tài khoản trên UCP trước khi vào game. Thêm tính năng Fix Kẹt cho player bị crash hoặc stuck.',
                'content' => '',
                'added' => "- **Đăng ký qua UCP**: Người chơi mới khi kết nối vào server sẽ được hướng dẫn truy cập **my.saw-mp.com** để đăng ký tài khoản. Sau khi đăng ký thành công, hãy kết nối lại vào game.\n- **Fix Kẹt**: Nếu bạn bị kẹt, crash hoặc rơi vào chỗ không thoát ra được, hãy truy cập UCP → bấm nút **Fix Kẹt** → kết nối lại vào server. Bạn sẽ được đưa về vị trí an toàn.",
                'changed' => null,
                'fixed' => null,
                'removed' => "- Đăng ký tài khoản trực tiếp trong game (nay chuyển sang UCP)",
                'status' => 'published',
                'published_at' => '2026-05-30 15:00:00',
                'created_at' => '2026-05-30 15:00:00',
            ],
            [
                'title' => 'Cho phép sử dụng ReShade',
                'slug' => 'allow-reshade-20260529',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'ReShade — phần mềm chỉnh đồ họa phổ biến — nay được phép sử dụng trên server.',
                'content' => '',
                'added' => null,
                'changed' => "- Người chơi có thể sử dụng ReShade để cải thiện đồ họa mà không bị hệ thống anti-cheat chặn",
                'fixed' => null,
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-29 12:00:00',
                'created_at' => '2026-05-29 12:00:00',
            ],
            [
                'title' => 'Hệ thống đào khoáng AFK',
                'slug' => 'afk-mining-20260527',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Thêm hệ thống đào khoáng sản tự động — kiếm tiền ngay cả khi AFK.',
                'content' => '',
                'added' => "- **Đào khoáng AFK**: Đứng gần các điểm khoáng sản trên map để tự động đào. Hệ thống hỗ trợ AFK nên bạn không cần thao tác liên tục.\n- **5 loại khoáng sản**: Bạc, Niken, Vàng, Đồng, Crom — mỗi loại có giá trị khác nhau.\n- **56 điểm khoáng sản** rải rác khắp bản đồ.\n- Khoáng sản có thể dùng để chế tạo vũ khí hoặc bán lấy tiền.\n- Nhận EXP khi đào khoáng.",
                'changed' => null,
                'fixed' => null,
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-27 02:00:00',
                'created_at' => '2026-05-27 02:00:00',
            ],
            [
                'title' => 'Cướp ATM & Cửa hàng + Đói Khát + Trộm Xe',
                'slug' => 'robbery-hunger-tromxe-20260526',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Thêm hệ thống cướp ATM và cửa hàng 24/7, cải tiến hệ thống đói khát, thêm nghề trộm xe, đồng hồ tốc độ mới.',
                'content' => '',
                'added' => "- **Cướp ATM**: Sử dụng lệnh tương tác gần ATM để cướp. Cần dụng cụ bẻ khóa. Nhận $35.000 - $70.000 tiền bẩn. Cảnh sát sẽ nhận được báo động.\n- **Cướp cửa hàng 24/7**: Tương tự ATM nhưng tại các cửa hàng tiện lợi. Nhận $60.000 - $110.000 tiền bẩn.\n- **Yêu cầu**: Phải có ít nhất 2 cảnh sát trực tuyến. Khi cướp thành công sẽ bị truy nã +2 sao.\n- **Thời gian**: 10 giây bẻ khóa → báo động cảnh sát → 3 phút thu thập tiền. Mỗi người chỉ được cướp 1 lần mỗi 15 phút.\n- **Nghề trộm xe**: Chọn nghề, tìm xe mục tiêu, bẻ khóa và bán lại. Cần chế tạo dụng cụ bẻ khóa từ vật liệu.\n- **Đồng hồ tốc độ mới**: Giao diện đẹp hơn, hiển thị chi tiết hơn.",
                'changed' => "- **Hệ thống đói khát**: Giao diện mới dạng icon thay vì thanh bar. Có thể ăn tại nhà hàng để hồi phục. Khi quá đói sẽ bị trượt ngã khi chạy.\n- Thông báo khi sử dụng vật liệu từ tủ đồ tổ chức",
                'fixed' => "- Sửa lỗi vũ khí bị mất khi chết\n- Sửa lỗi mất kết nối khi spawn xe tổ chức",
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-26 14:00:00',
                'created_at' => '2026-05-26 14:00:00',
            ],
            [
                'title' => 'Nghề câu cá & Hệ thống cần sa',
                'slug' => 'fisherman-cannabis-20260525',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Fix luồng bán cá cho nghề câu cá. Thêm hệ thống trồng và bán cần sa.',
                'content' => '',
                'added' => "- **Hệ thống cần sa**: Trồng cây cần sa, chăm sóc, thu hoạch và bán lấy tiền. Có thể bị cảnh sát phát hiện.",
                'changed' => null,
                'fixed' => "- Sửa lỗi nghề câu cá không bán được cá",
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-25 18:00:00',
                'created_at' => '2026-05-25 18:00:00',
            ],
            [
                'title' => 'Balo: Cho đồ, Gộp stack, Thông báo + Nhạc đăng nhập',
                'slug' => 'balo-polish-law-20260521',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Hoàn thiện hệ thống balo: cho item người khác, gộp stack, thông báo item mới, sử dụng nhanh. Thêm nhạc nền khi đăng nhập.',
                'content' => '',
                'added' => "- **Cho item**: Nhấp chuột phải vào item trong balo để gửi cho người chơi khác gần đó.\n- **Gộp stack**: Items cùng loại tự động gộp vào một slot để tiết kiệm chỗ.\n- **Thông báo**: Khi nhận item mới sẽ có popup thông báo trên màn hình.\n- **Sử dụng nhanh**: Dùng item trực tiếp từ balo mà không cần mở menu.\n- **Nhạc nền đăng nhập**: Nghe nhạc chờ khi đang đăng nhập vào server.\n- Mở khóa vũ khí M4 LAW và AK LAW trong tủ đồ tổ chức.",
                'changed' => null,
                'fixed' => "- Sửa nhiều lỗi giao diện balo\n- Đạn dược đồng bộ đúng khi cất vũ khí vào balo\n- Sửa lỗi mất đạn khi chết",
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-21 23:00:00',
                'created_at' => '2026-05-21 23:00:00',
            ],
            [
                'title' => 'Hệ thống Balo & Túi đồ hoàn toàn mới',
                'slug' => 'inventory-balo-20260520',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Hệ thống balo hoàn toàn mới: 84 slot chứa đồ, 7 slot vũ khí, chế tạo, giao dịch, và nhiều tính năng khác.',
                'content' => 'Bản cập nhật lớn nhất từ trước đến nay — hệ thống túi đồ hoàn toàn mới cho SAW Community.',
                'added' => "- **Túi đồ 84 slot**: Chứa được nhiều loại vật phẩm khác nhau — khoáng sản, vũ khí, thức ăn, dụng cụ, v.v.\n- **7 slot vũ khí**: Trang bị tối đa 7 vũ khí mang theo người.\n- **Chế tạo vũ khí**: Dùng khoáng sản + tiền + EXP để chế tạo vũ khí tại bàn chế tạo.\n- **Giao dịch**: Giao dịch vật phẩm với người chơi khác qua menu.\n- **Rớt/nhặt vũ khí**: Vũ khí rơi ra khi chết, người khác có thể nhặt.\n- **Bán vũ khí**: Bán vũ khí cho người chơi khác qua lệnh tương tác.\n- **Hệ thống hướng dẫn**: Tab hướng dẫn tích hợp sẵn trong balo.\n- **Vũ khí LAW**: Sát thương gấp 10.9 lần vũ khí thường, chỉ dành cho tổ chức thực thi pháp luật.\n- **Tủ đồ LAW**: Lệnh riêng để lấy vũ khí LAW từ tủ đồ tổ chức.\n- **Nghề Pizza**: Bỏ thời gian chờ, tăng khoảng cách giao hàng, bao gồm cả nhà chưa có chủ.\n- **Hệ thống tội phạm**: Hiển thị mức sao truy nã chi tiết hơn.\n- **Mapping SAPD & SFA**: Tòa nhà cảnh sát và SFA được trang hoàng mới.",
                'changed' => "- Giao diện balo chuyển sang dạng dialog (dễ sử dụng hơn trên cả PC và điện thoại)\n- Pizza Boy: bỏ thời gian chờ giữa các chuyến, tăng 50% thời gian giao",
                'fixed' => "- Sửa lỗi exploit thoát game khi chết (anti ESC bug)\n- Không thể nói chuyện IC khi đang chết\n- Tự động đưa đến bệnh viện khi rơi khỏi bản đồ\n- Sửa lỗi teleport đến nhà tù\n- Sửa nhiều lỗi giao diện balo",
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-20 23:00:00',
                'created_at' => '2026-05-20 23:00:00',
            ],
            [
                'title' => 'Việt hóa toàn diện & Hệ thống Chết mới',
                'slug' => 'viet-hoa-death-system-20260519',
                'type' => 'game',
                'inline' => true,
                'author' => 'Miho',
                'description' => 'Việt hóa toàn bộ hệ thống lệnh trong game. Thêm trạng thái "Đã chết" cho hệ thống chết. Thêm lệnh tạo băng đảng/tổ chức.',
                'content' => 'Ngày đầu tiên ra mắt SAW Community — Việt hóa toàn diện và nhiều tính năng gameplay mới.',
                'added' => "- **Việt hóa toàn diện**: Hơn 170 lệnh và alias tiếng Việt. Tất cả lệnh chat đều có phiên bản tiếng Việt.\n- **Trạng thái Đã chết**: Khi bị hạ gục, bạn sẽ ở trạng thái chờ cứu thương trong một khoảng thời gian trước khi tự động đến bệnh viện. VIP được chờ ngắn hơn.\n- **Tạo băng đảng**: Lệnh tạo family/faction mới với alias tiếng Việt.\n- **Quản lý tội phạm**: Thêm/xóa tội phạm động cho hệ thống cảnh sát.\n- **Giới hạn súng newbie**: Người chơi mới không thể sử dụng vũ khí trong 2 giờ đầu để tránh bị ức hiếp.",
                'changed' => "- Người chơi mới sẽ nhận thông báo chào mừng dựa trên số giờ chơi thay vì cấp độ",
                'fixed' => "- Sửa nhiều lỗi lệnh admin\n- Sửa lỗi cửa chặn tất cả người chơi\n- Sửa lỗi nghề quét rác không hoạt động\n- Sửa lỗi safezone\n- Sửa lỗi hiển thị turf/poll",
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-19 23:00:00',
                'created_at' => '2026-05-19 23:00:00',
            ],
            [
                'title' => 'SAW Community chính thức ra mắt!',
                'slug' => 'infrastructure-openmp',
                'type' => 'release',
                'inline' => false,
                'author' => 'Miho',
                'description' => 'SAW Community chính thức ra mắt trên nền tảng open.mp — server SA-MP thế hệ mới với hiệu suất tốt hơn và nhiều tính năng hiện đại.',
                'content' => "SAW Community chính thức mở cửa đón người chơi!\n\n**Về server:**\n- Chạy trên nền tảng **open.mp** — phiên bản nâng cấp của SA-MP với hiệu suất ổn định hơn, hỗ trợ nhiều người chơi hơn.\n- Database riêng biệt, dữ liệu được lưu trữ an toàn.\n- Website UCP tại **my.saw-mp.com** — đăng ký tài khoản, xem thông tin nhân vật, quản lý tài khoản.\n\n**Cộng đồng:**\n- Discord: Tham gia qua link trên UCP\n- Thể loại: Roleplay\n- Ngôn ngữ: Tiếng Việt\n\nChào mừng bạn đến với SAW Community!",
                'added' => null,
                'changed' => null,
                'fixed' => null,
                'removed' => null,
                'status' => 'published',
                'published_at' => '2026-05-19 00:00:00',
                'created_at' => '2026-05-19 00:00:00',
            ],
        ];

        foreach ($notes as $note) {
            ReleaseNote::create(array_merge($note, [
                'image' => null,
            ]));
        }
    }
}
